[platformio]
; default_envs = key-cast-atom-matrix
; default_envs = key-cast-atom-lite

[env]
platform = espressif32@^7.0.1
platform_packages =
    platformio/framework-arduinoespressif32@^3.20017
    platformio/tool-esptoolpy@^2.41100.0
framework = arduino

board_build.f_cpu = 240000000L
board_build.f_flash = 80000000L
board_build.mcu = esp32
board_build.flash_mode = dio

monitor_speed = 115200
monitor_filters = esp32_exception_decoder, time
upload_speed = 1500000

build_flags = 
    -DSERIAL_BAUDRATE=${this.monitor_speed}
lib_deps =

lib_ldf_mode = deep

# ---------------------------------------------------------------------------
# Build Targets
# ---------------------------------------------------------------------------

[build-target]
extends = release
; extends = debug

[release]
build_type = release
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=3
    -DLOG_LOCAL_LEVEL=3

[debug]
build_type = debug
build_flags =
    ${env.build_flags}
    -DCORE_DEBUG_LEVEL=4
    -DLOG_LOCAL_LEVEL=4
    -DDEBUG

# ---------------------------------------------------------------------------
# Boards
# ---------------------------------------------------------------------------

[m5stack-atom]
board = m5stack-atom
build_flags =
    ; -DARDUINO_M5Stack_ATOM
    ${env.build_flags}
    -DRGB_LED_PIN=GPIO_NUM_27
    -DRGB_LED_ORDER=GRB
    -DBUTTON_PIN=GPIO_NUM_39
    -DARDUINO_M5STACK_ATOM
lib_deps =
    ${env.lib_deps}
    JC_Button

[m5stack-atom-matrix]
extends = m5stack-atom
build_flags =
    ${m5stack-atom.build_flags}
    -DARDUINO_M5STACK_ATOM_MATRIX
    -DNUM_RGB_LEDS=25
lib_deps =
    ${m5stack-atom.lib_deps}

[m5stack-atom-lite]
extends = m5stack-atom
build_flags =
    ${m5stack-atom.build_flags}
    -DARDUINO_M5STACK_ATOM_LITE
    -DNUM_RGB_LEDS=1
lib_deps =
    ${m5stack-atom.lib_deps}

# ---------------------------------------------------------------------------
# Libraries
# ---------------------------------------------------------------------------

[esp-now-manager]
build_flags =
    -DESP_NOW_CHANNEL=0
lib_deps = 
    m5stack-espnow=https://github.com/3110/m5stack-esp-now.git#v0.0.2

[ble-keyboard]
build_flags =
    -DUSE_NIMBLE
lib_deps =
    https://github.com/T-vK/ESP32-BLE-Keyboard.git#0.3.0
    h2zero/NimBLE-Arduino@^1.4.3

[ble-key-cast]
extends = esp-now-manager, ble-keyboard, build-target
build_flags =
    ${esp-now-manager.build_flags}
    ${ble-keyboard.build_flags}
    ${build-target.build_flags}
    -DCAST_KEY_DEVICE_MANUFACTURER=\"M5Stack\"
    -DCAST_KEY_CHANNEL=0
lib_deps =
    ${esp-now-manager.lib_deps}
    ${ble-keyboard.lib_deps}
custom_firmware_suffix = bin
custom_firmware_version_file = lib/BLEKeyCast/include/BLEKeyCast.hpp
custom_firmware_dir = firmware
custom_firmware_name = ble_key_cast
extra_scripts =
    ; pre:erase_nvs.py
    post:generate_user_custom.py

# ---------------------------------------------------------------------------
# Envronments
# ---------------------------------------------------------------------------

[env:key-cast-atom-lite]
extends = m5stack-atom-lite, ble-key-cast
build_flags = 
    ${m5stack-atom-lite.build_flags}
    ${ble-key-cast.build_flags}
    -DCAST_KEY_SEND_KEY=0x31 ; '1'
    -DCAST_KEY_DEVICE_NAME=\"KC_Lite\"
lib_deps = 
    ${m5stack-atom-lite.lib_deps}
    ${ble-key-cast.lib_deps}
custom_firmware_target = m5atom_lite
; upload_port = /dev/cu.usbserial-XXXXXXXXXX ; macOS
; upload_port = COM14                        ; Windows
; monitor_port = ${this.upload_port}

[env:key-cast-atom-matrix]
extends = m5stack-atom-matrix, ble-key-cast
build_flags = 
    ${m5stack-atom-matrix.build_flags}
    ${ble-key-cast.build_flags}
    -DCAST_KEY_SEND_KEY=0x32 ; '2'
    -DCAST_KEY_DEVICE_NAME=\"KC_Matrix\"
lib_deps = 
    ${m5stack-atom-matrix.lib_deps}
    ${ble-key-cast.lib_deps}
custom_firmware_target = m5atom_matrix
; upload_port = /dev/cu.usbserial-XXXXXXXXXX ; macOS
; upload_port = COM16                        ; Windows
; monitor_port = ${this.upload_port}
